# Generated by Django 2.1.5 on 2021-01-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_auto_20210124_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.TextField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.TextField(default=0),
        ),
    ]
