# Generated by Django 2.1.5 on 2021-01-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0003_auto_20210124_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
