# Generated by Django 2.1.5 on 2021-02-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0005_auto_20210211_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='done', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(default='project', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.TextField(default='link'),
        ),
    ]
